version: '3'
services:
  mongodb:
    container_name: mongodb
    image: mongo:3.6.0
    ports:
      - "27017:27017"
    volumes:
      - dbvolume:/data
    environment: {
      AUTH: "no"
    }
  backend:
    container_name: backend
    build: ./backend/
    restart: always
    ports:
      - "8080:8080"
    depends_on: #This is a lie
      - mongodb
volumes:
  dbvolume: { }
